name: Mosaic Church
favicon: null
layout_spectrum: 0.17835
typography_spectrum: 0.24523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cb0002'
    - '#fbc19b'
    - '#ce564e'
    - '#c38c8d'
    - '#fcf0e5'
  brandStrength: 0.2713841204531491
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
